In [1]:
from requests_html import HTMLSession
import pandas as pd

In [2]:
class Fish(object):
    def __init__(self, page_num):
        session = HTMLSession()
        self.page_num = page_num
        self.url = f'https://www.km28.com/gp_chart/zjklse/0/{self.page_num}.html'
        self.r = session.get(self.url)
    def get_valid(self, tr):
        try:
            if tr.attrs['id'].startswith('20') or tr.attrs['id']=='menuitem':
                return True
        except:
            return False
    def get_table(self):
        tr = self.r.html.find('#chartsTable',first=True).find('tr')
        tr_text = [_.text.split()[:6] for _ in tr if self.get_valid(_)]
        head = tr_text[0]
        head_text = [head[0]] + [head[1]+str(_) for _ in range(1,6)]
        df = pd.DataFrame(data=tr_text[1:], columns=head_text)
        return df

In [3]:
foo = Fish(20)

In [4]:
foo.get_table()

             期号 开奖号码1 开奖号码2 开奖号码3 开奖号码4 开奖号码5
0   20180702075    08    06    11    02    04
1   20180702076    04    10    07    05    09
2   20180702077    11    07    05    09    12
3   20180702078    04    10    07    01    03
4   20180702079    12    01    08    09    04
5   20180702080    06    01    09    07    05
6   20180703001    12    05    09    07    02
7   20180703002    10    07    09    06    08
8   20180703003    04    06    02    11    08
9   20180703004    09    05    06    01    12
10  20180703005    11    06    05    10    09
11  20180703006    03    05    04    07    11
12  20180703007    05    01    08    10    11
13  20180703008    05    03    01    04    06
14  20180703009    12    01    08    02    04
15  20180703010    11    08    03    05    06
16  20180703011    07    11    06    09    10
17  20180703012    06    03    12    09    08
18  20180703013    02    12    06    01    10
19  20180703014    12    10    04    07    06